<?php

namespace App\Services\CustomerIdentity;

use App\Models\Customer;
use App\Models\CustomerAddress;
use Illuminate\Support\Facades\DB;

/**
 * CUSTOMER-001B — every mutation of a customer's address book goes through
 * here, so the invariants hold everywhere (checkout, settings, future
 * wallet): exactly one default among active addresses, phone numbers
 * normalized to E.164 when possible, whitespace trimmed, and deleting or
 * archiving the default promotes another active address automatically.
 */
class AddressBookService
{
    public function __construct(private PhoneNumberService $phones)
    {
    }

    public function create(Customer $customer, array $data): CustomerAddress
    {
        $data = $this->clean($data);

        return DB::transaction(function () use ($customer, $data) {
            $makeDefault = ($data['is_default'] ?? false)
                || ! $customer->addresses()->active()->exists();

            unset($data['is_default']);
            $address = $customer->addresses()->create($data + ['is_active' => true]);

            if ($makeDefault) {
                $this->setDefault($address);
            }

            return $address;
        });
    }

    public function update(CustomerAddress $address, array $data): CustomerAddress
    {
        $data = $this->clean($data);
        $makeDefault = (bool) ($data['is_default'] ?? false);
        unset($data['is_default']);

        return DB::transaction(function () use ($address, $data, $makeDefault) {
            $address->update($data);
            if ($makeDefault && ! $address->is_default) {
                $this->setDefault($address);
            }

            return $address->refresh();
        });
    }

    /** Make this the single default; only active addresses may be default. */
    public function setDefault(CustomerAddress $address): void
    {
        DB::transaction(function () use ($address) {
            CustomerAddress::where('customer_id', $address->customer_id)
                ->whereKeyNot($address->getKey())
                ->update(['is_default' => false]);

            $address->forceFill(['is_default' => true, 'is_active' => true])->save();
        });
    }

    /** Soft delete; if it was the default, promote the newest active address. */
    public function delete(CustomerAddress $address): void
    {
        DB::transaction(function () use ($address) {
            $wasDefault = $address->is_default;
            $address->forceFill(['is_default' => false])->save();
            $address->delete();

            if ($wasDefault) {
                $this->promoteNextDefault($address->customer_id);
            }
        });
    }

    /** Archive (hide from checkout) without losing history. */
    public function archive(CustomerAddress $address): void
    {
        DB::transaction(function () use ($address) {
            $wasDefault = $address->is_default;
            $address->forceFill(['is_active' => false, 'is_default' => false])->save();

            if ($wasDefault) {
                $this->promoteNextDefault($address->customer_id);
            }
        });
    }

    public function restore(CustomerAddress $address): void
    {
        $address->forceFill(['is_active' => true])->save();
    }

    /** Copy an address (never copies default status). */
    public function duplicate(CustomerAddress $address): CustomerAddress
    {
        $copy = $address->replicate(['uuid', 'is_default']);
        $copy->uuid       = null; // regenerated by the model
        $copy->is_default = false;
        $copy->is_active  = true;
        $copy->label      = mb_substr($address->label.' '.__('customer_address.copy_suffix'), 0, 50);
        $copy->save();

        return $copy;
    }

    /**
     * Country-aware validation rules for an address payload, built from
     * config/customer_address.php — required fields and postcode format
     * differ per country; nothing is hardcoded to Thailand.
     *
     * @return array<string, array<int, mixed>>
     */
    public function rulesFor(?string $country): array
    {
        $countries = config('customer_address.countries', []);
        $country   = array_key_exists($country ?? '', $countries)
            ? $country
            : config('customer_address.default_country');
        $config = $countries[$country];

        $required = fn (string $field) => in_array($field, $config['required'], true) ? 'required' : 'nullable';

        $rules = [
            'label'          => ['required', 'string', 'max:50'],
            'recipient_name' => ['required', 'string', 'max:150'],
            'phone'          => ['nullable', 'string', 'max:30'],
            'country'        => ['required', 'string', \Illuminate\Validation\Rule::in(array_keys($countries))],
            'line1'          => [$required('line1'), 'string', 'max:255'],
            'line2'          => ['nullable', 'string', 'max:255'],
            'postal_code'    => [$required('postal_code'), 'string', 'max:16', 'regex:'.($config['postal_code_pattern'] ?? '/^.{1,16}$/')],
            'building'       => ['nullable', 'string', 'max:120'],
            'floor'          => ['nullable', 'string', 'max:20'],
            'unit'           => ['nullable', 'string', 'max:50'],
            'landmark'       => ['nullable', 'string', 'max:255'],
            'delivery_instructions' => ['nullable', 'string', 'max:500'],
            'is_default'     => ['nullable', 'boolean'],
        ];

        foreach (['admin_area_1', 'admin_area_2', 'admin_area_3', 'admin_area_4'] as $area) {
            $rules[$area] = isset($config['levels'][$area])
                ? [$required($area), 'string', 'max:120']
                : ['prohibited'];
        }

        return $rules;
    }

    private function promoteNextDefault(int $customerId): void
    {
        CustomerAddress::where('customer_id', $customerId)
            ->active()
            ->latest('updated_at')
            ->first()
            ?->forceFill(['is_default' => true])->save();
    }

    /**
     * An unsaved, sanitized address instance — used at checkout when the
     * customer types a one-off address without saving it to the book.
     */
    public function makeUnsaved(array $data): CustomerAddress
    {
        return new CustomerAddress($this->clean($data));
    }

    /** Trim every string; normalize the contact phone to E.164 when possible. */
    private function clean(array $data): array
    {
        foreach ($data as $key => $value) {
            if (is_string($value)) {
                $trimmed    = trim($value);
                $data[$key] = $trimmed === '' ? null : $trimmed;
            }
        }

        if (! empty($data['phone'])) {
            $data['phone'] = $this->phones->normalize($data['phone'], $data['country'] ?? null)
                ?? $data['phone'];
        }

        return $data;
    }
}
